version: "3"
services:
  #Container for Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    hostname: elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
  #Container for Kibana
  kibana:
    #Match the version numbers of elasticsearch and kibana images
    image: docker.elastic.co/kibana/kibana:6.8.23
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  # MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3301:3302"
    volumes:
      - pgdata:/var/lib/mysql
  rails:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - elasticsearch
    ports:
      - 3000:3000
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_URL: http://elasticsearch:9200
    tty: true
    stdin_open: true
    volumes:
      #Abandon consistency with delegated and focus on performance
      - .:/myChat:delegated
#Volume used by elasticsearch and db
volumes:
  esdata:
  pgdata:
